---

- apt:
    state: present
    name: "{{item}}"
  with_items:
    - nginx

- name: Install nginx
  command: >
    apt-get -y install nginx
  notify: reload nginx

- name: Copy nginx.conf
  copy:
    src: conf/nginx.conf
    dest: /etc/nginx/

- name: Copy default.conf
  copy:
    src: conf/default.conf
    dest: /etc/nginx/sites-available/default

- name: Change permission in access.log, error.log
  become: True
  command: >
    chmod 777 /var/log/nginx/access.log
    chmod 777 /var/log/nginx/error.log
  