---
- apt:
    state: present
    name: "{{item}}"
  with_items:
    - nginx

- name: "Install nginx"
  command: >
    apt-get update
    apt-get -y install nginx
  ignore_errors: yes
  notify: reload nginx

# - copy:
#     src: /remote_user
#     dest: /etc/nginx/sites-available
#     remote_src: yes
#   notify: reload nginx
