---

- name: "Install MySQL"
  become: True
  shell: "DEBIAN_FRONTEND=noninteractive apt install -y mysql-server"

- name: Uncomment A Line Bind-Address = 127.0.0.1
  replace: >
    dest=/etc/mysql/mysql.conf.d/mysqld.cnf
    regexp='^bind-address'
    replace='#bind-address'

- name: copy my.cnf
  lineinfile:
    dest=/etc/mysql/my.cnf
    line={{ item }}
  with_items:
    - '[mysqld]'
    - 'default-authentication-plugin=mysql_native_password'
    - 'slow_query_log-file = /var/log/mysql/mysql-slow.log'
    - 'long_query_time = 0'
    - 'slow_query_log = 1'
  notify: restart mysql

- name: Install pip
  become: True
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present

- name: Create MySQL Database
  mysql_db: name={{ mysql_database }} state=present login_host=% login_user=root login_unix_socket=/var/run/mysqld/mysqld.sock

- name: Create MySQL User
  mysql_user: login_host=% priv="{{ mysql_database }}.*:ALL" login_unix_socket=/var/run/mysqld/mysqld.sock name={{ mysql_user }} password={{ mysql_password }}

- name: Create SlowQueryLog and Change Permission
  become: True
  copy:
    src: conf/mysql-slow.log
    dest: /var/log/mysql/
    mode: 0777

- name: create my.cnf in /home/ubuntu
  become: True
  copy:
    src: conf/my.cnf
    dest: /home/ubuntu/
