---

- name: unzip go 1.17.7
  unarchive:
    src: https://dl.google.com/go/go1.17.7.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  ignore_errors: yes
 
- name: copy goenv.sh
  copy:
    src: "{{ item.src }}"
    dest: "/etc/profile.d/{{ item.dest }}"
    mode: 0755
    backup: no
    owner: root
    group: root
  loop:
    - { src: roles/go/files/goenv.sh, dest: . }
 
- name: source /etc/profile.d/goenv.sh
  shell: bash -lc "source /etc/profile.d/goenv.sh"
  ignore_errors: yes
  