---

- apt:
    state: present
    name: "{{ item }}"
  with_items:
    - git
    - sudo

- name: Copy db_setenv.sh
  copy:
    src: "{{ item.src }}"
    dest: "/etc/profile.d/{{ item.dest }}"
    mode: 0755
    backup: no
    owner: ubuntu
    group: ubuntu
  loop:
    - { src: roles/common/files/db_setenv.sh, dest: . }

- name: Execute /etc/profile.d/db_setenv.sh
  shell: bash -lc "source /etc/profile.d/db_setenv.sh"

- name: Set AcceptEnv
  copy:
    src: conf/sshd_config
    dest: /etc/ssh/sshd_config
    owner: ubuntu
    group: ubuntu
    mode: 0600
  notify: restart ssh

- name: Set Private Key
  copy:
    src: /Users/kumao/Downloads/id_rsa
    dest: /home/{{ansible_ssh_user}}/.ssh/id_rsa
    owner: ubuntu
    group: ubuntu
    mode: 0600
  notify: restart ssh
