---

- apt:
    state: present
    name: "{{ item }}"
  with_items:
    - git
    - sudo

- name: copy db_setenv.sh
  copy:
    src: "{{ item.src }}"
    dest: "/etc/profile.d/{{ item.dest }}"
    mode: 0755
    backup: no
    owner: root
    group: root
  loop:
    - { src: roles/common/files/db_setenv.sh, dest: . }

- name: execute /etc/profile.d/db_setenv.sh
  shell: bash -lc "source /etc/profile.d/db_setenv.sh"

- name: Set AcceptEnv
  copy:
    src: conf/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0600

- name: Set Private Key
  copy:
    src: /Users/kumao/.ssh/isucon_github_rsa
    dest: /home/{{ansible_ssh_user}}/.ssh/id_rsa
    owner: root
    group: root
    mode: 0600